name: zap_scan
description: Flutter scanning package for cards, barcodes, and IATA boarding passes using on-device OCR and EMV NFC.
version: 1.1.2
homepage: https://github.com/devang-singh/zap_scan
repository: https://github.com/devang-singh/zap_scan
issue_tracker: https://github.com/devang-singh/zap_scan/issues
topics:
  - scanner
  - ocr
  - nfc
  - card
  - barcode

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  camera: ^0.12.0
  google_mlkit_commons: ^0.11.1
  nfc_manager: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.devangsingh.zap_scan
        pluginClass: ZapScanPlugin
      ios:
        pluginClass: ZapScanPlugin
      macos:
        pluginClass: ZapScanPlugin
      web:
        pluginClass: ZapScanWeb
        fileName: src/web/zap_scan_web.dart
